WIP: 類似検索できるようにする
Wondershake/gettyimages-api_ruby pull request #1
Opened 2016-09-09 10:09 UTC by sskyu

https://github.com/Wondershake/locari/pull/1786

動作確認中。

2016-09-15 07:19 UTC, sskyu commented on ConnectSDK/lib/ImagesRequest.rb
> +end
全行差分が出ているのはタブからスペースへ置換したためです。
あとは rubocop で指摘されている部分はなるべく直してみました。
まだ2つ warning が出てますが放っています。
```
L1: The name of this source file should use snake_case.
L3: Missing top-level class documentation comment.
```

2016-09-15 08:58 UTC, sskyu commented
@mmyoji  差分のところだけレビューお願いします!

2016-09-15 09:03 UTC, mmyoji commented on ConnectSDK/lib/ImagesRequest.rb
> -    return "here"
これウケますねw

2016-09-15 09:08 UTC, mmyoji commented on ConnectSDK/lib/ImagesRequest.rb
> +  @search_route = CONNECT_ROUTE
こういうことできるんですね... :thinking_face:

2016-09-15 09:15 UTC, mmyoji commented on ConnectSDK/lib/ImagesRequest.rb
> +  @search_route = CONNECT_ROUTE
あ、調べてみましたが、以下のような結果になるのでこの書き方はマズイですね...

```rb
class Person
  @foo = "foo"

  def run
    puts @foo
  end
end

person = Person.new
person.run #=> nil
person.instance_variable_get :@foo #=> nil
person.class.instance_variable_get :@foo #=> "foo"
```

なので、（元のコードは相当キモイですが） `class_variable` のままで使っておいた方が無難ですmm

（現状必ず `#with_id` or `#with_similar_id` を通るので問題はないっちゃないですが）

2016-09-15 09:20 UTC, mmyoji requested changes
指摘した点修正お願いしますmm

2016-09-15 09:20 UTC, mmyoji commented
元のコード結構すごいので、読むの大変ですね... 😓

2016-09-15 09:21 UTC, sskyu commented on ConnectSDK/lib/ImagesRequest.rb
> +  @search_route = CONNECT_ROUTE
なるほど！直します 🙋

2016-09-15 09:50 UTC, sskyu commented
b0aa690　このコミットで修正してみました！ご確認お願いします :bow:

2016-09-15 13:24 UTC, mmyoji approved these changes
![lgtm](https://38.media.tumblr.com/a4ea37c1dceaab3849fa4c509d4fe181/tumblr_n87y30PaXA1re1y0eo1_500.gif)

2016-09-15 13:25 UTC, mmyoji commented
画像でなかったーw

2016-09-15 13:25 UTC, mmyoji commented
LGTM!!!

2016-09-15 13:55 UTC, sskyu commented
ありがとうございます! 明日マージします!

2016-09-16 04:27 UTC, sskyu commented
マージします!

2016-09-16 04:27 UTC, merged